client_config_backend: settings
client_config:
    client_id: 662985110113-kmprcvg5lne7g2f89ste2hb3o6eeak1g
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive